### ISSUE TITLE
doesn't work with list elements created at runtime

### ISSUE THREAD

**Issue by mariusa** [shvetsgroup/jquery.multisortable#1]
One can set jquery.sortable() on an empty ul, which later will get populated with li's.

multisortable will give an error, as it tries to access inexistent children with
var tagName = list.children().get(0).tagName

Please enable it to work with  list elements created at runtime

**Comment by iamvery** [comment]
Thanks for your input! At this time I don't have plans to devote any effort in improving this library (its just a GitHub port + tests of someone else's code), but if you'd like to give it a stab and submit a pull request, I'll certainly have a look at it :).

**Comment by iamvery** [comment]
Just as a heads up, I just pushed a v0.1.3 that attempts to address this issue. I did this by defining the sortable lists "items" as "li" by default. One gotcha to this solution is the traditional default of "> *" won't work with the script because of how I'm preventing unselected items from being sorted. You'll need to use non-generic selectors for a multisortable's "items".

Hope this helps if it still applies to you!
