### ISSUE TITLE
Cancel Option 

### ISSUE THREAD

**Issue by ianwallen** [shvetsgroup/jquery.multisortable#4]
Is it possible to have a cancel option that the elements are sortable but not selectable?

i.e. 

```
<table>
  <tbody class="multisortable">
        <tr><td>1</td><td class="noselect">data:<input type="text"></td></tr>
        <tr><td>2</td><td class="noselect">data:<input type="text"></td></tr>
        <tr><td>3</td><td class="noselect">data:<input type="text"></td></tr>
        <tr><td>4</td><td class="noselect">data:<input type="text"></td></tr>
   </tbody>
</table>
```

In this case, I would like to be able to sort the table by selecting the items from the first column and not the second.

I believe this is possible with jquery sortable by specifying the following option

cancel: ".noselect"

Thank you

**Comment by iamvery** [comment]
Its been awhile since I've looked at the code here, but as I remember it is designed to allow "sort" only on items which are selected. This slightly changes how vanilla jQuery sortable works.

Anyway, you're welcome to take a stab at implementing this functionality. Sounds like a good improvement :). I'll happily entertain pull requests!

**Comment by iamvery** [comment]
Closing for lack of communication.
